// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify
/*
 * Copyright 2025 Alexandre Mahdhaoui
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package mockebpfstruct

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockFIFO creates a new instance of MockFIFO. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFIFO[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFIFO[T] {
	mock := &MockFIFO[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFIFO is an autogenerated mock type for the FIFO type
type MockFIFO[T any] struct {
	mock.Mock
}

type MockFIFO_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockFIFO[T]) EXPECT() *MockFIFO_Expecter[T] {
	return &MockFIFO_Expecter[T]{mock: &_m.Mock}
}

// Done provides a mock function for the type MockFIFO
func (_mock *MockFIFO[T]) Done() <-chan struct{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Done")
	}

	var r0 <-chan struct{}
	if returnFunc, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}
	return r0
}

// MockFIFO_Done_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Done'
type MockFIFO_Done_Call[T any] struct {
	*mock.Call
}

// Done is a helper method to define mock.On call
func (_e *MockFIFO_Expecter[T]) Done() *MockFIFO_Done_Call[T] {
	return &MockFIFO_Done_Call[T]{Call: _e.mock.On("Done")}
}

func (_c *MockFIFO_Done_Call[T]) Run(run func()) *MockFIFO_Done_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFIFO_Done_Call[T]) Return(valCh <-chan struct{}) *MockFIFO_Done_Call[T] {
	_c.Call.Return(valCh)
	return _c
}

func (_c *MockFIFO_Done_Call[T]) RunAndReturn(run func() <-chan struct{}) *MockFIFO_Done_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function for the type MockFIFO
func (_mock *MockFIFO[T]) Subscribe() (<-chan T, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 <-chan T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (<-chan T, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() <-chan T); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFIFO_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockFIFO_Subscribe_Call[T any] struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
func (_e *MockFIFO_Expecter[T]) Subscribe() *MockFIFO_Subscribe_Call[T] {
	return &MockFIFO_Subscribe_Call[T]{Call: _e.mock.On("Subscribe")}
}

func (_c *MockFIFO_Subscribe_Call[T]) Run(run func()) *MockFIFO_Subscribe_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFIFO_Subscribe_Call[T]) Return(vCh <-chan T, err error) *MockFIFO_Subscribe_Call[T] {
	_c.Call.Return(vCh, err)
	return _c
}

func (_c *MockFIFO_Subscribe_Call[T]) RunAndReturn(run func() (<-chan T, error)) *MockFIFO_Subscribe_Call[T] {
	_c.Call.Return(run)
	return _c
}
